jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Limpiar dependencias previas
        run: |
          rm -rf node_modules package-lock.json

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Corregir permisos de node_modules
        run: chmod -R a+x node_modules

      - name: Ejecutar pruebas
        run: npm test -- --runInBand
